### ISSUE TITLE
[popups] Enabling tooltips can result in SublimeLinter closing other popups

### ISSUE THREAD

**Issue by jcberquist** [SublimeLinter/SublimeLinter3#565]
The tooltip support is very nice; I like it a lot. I did discover a minor issue with its interaction with other plugins using the popup (and I am not sure how much can be done about it).

Given how `close_tooltip()` is used, if there are any linter warnings in the view, and a key binding is used to trigger a popup on a line without a warning (e.g. using <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>ALT</kbd>+<kbd>p</kbd> to reveal scope names at the cursor position), then the popup will be immediately closed by SublimeLinter since using the key binding triggers the `on_selection_modified_async` event handler.

Since all plugins share access to the same popup (so to speak) I am not sure if anything can be done about this. Perhaps you could use a flag variable and the `on_hide` parameter of `show_popup` to track whether SublimeLinter has a currently opened popup? I don't know how feasible that is.

**Comment by xeron** [comment]
Enabling tooltips breaks other packages, for example `GitGutter` which shows diff in tooltips. `GitGutter` tooltips are still opening on-hover but they are being closed immediately in like 10ms if `SublimeLinter` tooltips are enabled.

**Comment by cmalard** [comment]
I'm having the same issue with [AutoFileName](https://github.com/BoundInCode/AutoFileName) :-)
Since it only uses tooltips to interact, it became unusable.

**Comment by deathaxe** [comment]
This issue can easily be fixed with 

```python
# don't let the popup flicker / fight with other packages
if view.is_popup_visible():
    return

# show popup
...
```

**Comment by jayfunk** [comment]
Not sure if this is the same issue, but when the tooltip opens it closes any autocomplete options. There is a very small window where the autocomplete is still available for selection. The reason I think this is the same issue is because I use AllAutoComplete.

**Comment by coagmano** [comment]
Can confirm that adding
```python
if active_view.is_popup_visible():
    return
```
to [line 460 of `sublimelinter.py`](https://github.com/SublimeLinter/SublimeLinter3/blob/master/sublimelinter.py#L460) improves the situation. 

You still get a flash hovering over gitgutter on a line with an error, but hovering over a gitgutter mark on a line with no error works fine

**Comment by maryqygao** [comment]
Added a PR with the suggestion change by @deathaxe. I also took out the `close_tooltip` method as it was closing other popups even when the caret is on a line without any lint errors. Would love to have some feedback on this.

**Comment by jayfunk** [comment]
Just adding a link to the PR: #579

**Comment by braver** [comment]
I'm consolidating this and other related issues in #619
